# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Cat.create([
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/us5eEBouq.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/ErmyshZhG.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/227.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/b60.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/e1o.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/afh.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/1dm.png'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/1no.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/8m8.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/ac3.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/2b0.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/dm1.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/cic.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MTkyNDg3Mg.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MTUwNzgxNQ.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/brg.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/2og.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/HW1MGAuGL.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/44f.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/c21.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/i5Bw5V_HM.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/a4m.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/aub.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/KJF8fB_20.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/1lf.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/pChQkK4hf.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/a0a.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/die.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/btt.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/cnn.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/LXgmee2q_.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/a4o.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/2lt.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/d3i.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/1it.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/9cu.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/TYQKhQ3mn.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/a8r.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/24d.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/pzIURJPra.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/ars.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/7tzyVT8_f.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/7kd.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/bn8.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/e07.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/3ij.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MTk5Mzc4Mw.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/3lj.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/wJyw82pIl.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/i-j1kCi3b.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/N-94oSJ5T.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MTk4OTQ5OQ.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/251.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/cdc.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/ahg.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/3bn.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/dnd.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/aaf.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/gU5wUcOuo.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/9hb.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MjA2NjAyOA.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/cir.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/MjAzODI4OQ.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/dVujvBqnu.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/aed.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/e4f.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/arf.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/bja.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/cno.jpg'},
    {name: Faker::FunnyName.two_word_name, img: 'https://cdn2.thecatapi.com/images/a93.jpg'},
    
])